"""second revision

Revision ID: 9918a7c0c94a
Revises: c3eba5d537f2
Create Date: 2024-06-10 10:22:46.602142

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9918a7c0c94a"
down_revision: Union[str, None] = "c3eba5d537f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "resumes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("TIMEZONE('utc', now() + interval '1day')"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "resumes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("timezone('utc'::text, now())"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
